# Generated by Django 5.2 on 2025-11-21 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_area_id', models.IntegerField(help_text='Номер региона')),
                ('name', models.CharField(help_text='Название региона', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_employer_id', models.IntegerField()),
                ('name', models.CharField(help_text='Название работодателя', max_length=150)),
                ('url', models.URLField(help_text='Ссылка на работодателя')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=25)),
                ('name', models.CharField(help_text='Опыт работы', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Профессиональная роль', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_from', models.IntegerField()),
                ('salary_to', models.IntegerField()),
                ('currency', models.CharField(help_text='Курс', max_length=15)),
                ('gross', models.BooleanField(help_text='ЗП указана до либо после вычета налогов')),
            ],
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Запрос по которому была найдена вакансия', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Навыки', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=25)),
                ('name', models.CharField(help_text='Формат работы', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=25)),
                ('name', models.CharField(help_text='График работы', max_length=50)),
                ('working_hours', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_vacancy_id', models.IntegerField(help_text='id вакансии у hh.ru')),
                ('name', models.CharField(help_text='Заголовок вакансии', max_length=255)),
                ('published_at', models.DateTimeField(help_text='Когда вакансия была опубликована в hh.ru')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='Когда запись появилась в БД')),
                ('url', models.URLField(help_text='Ссылка на вакансию')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hh_app.area')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hh_app.employer')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hh_app.experience')),
                ('professional_roles', models.ManyToManyField(to='hh_app.professionalrole')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hh_app.salary')),
                ('search_query', models.ManyToManyField(to='hh_app.searchquery')),
                ('skills', models.ManyToManyField(to='hh_app.skill')),
                ('work_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hh_app.workformat')),
                ('work_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hh_app.workschedule')),
            ],
        ),
    ]
