# Generated by Django 5.2 on 2025-11-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='salary_from',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary_to',
            field=models.IntegerField(null=True),
        ),
    ]
