# Generated by Django 5.2 on 2025-11-24 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_app', '0002_alter_salary_salary_from_alter_salary_salary_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hh_app.area'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hh_app.salary'),
        ),
    ]
